#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MyWeather.Resource", IsApplication=true)]

namespace MyWeather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010006
			public const int adSize = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int adSizes = 2130771975;
			
			// aapt resource value: 0x7f010008
			public const int adUnitId = 2130771976;
			
			// aapt resource value: 0x7f010003
			public const int buttonSize = 2130771971;
			
			// aapt resource value: 0x7f010002
			public const int circleCrop = 2130771970;
			
			// aapt resource value: 0x7f010004
			public const int colorScheme = 2130771972;
			
			// aapt resource value: 0x7f010001
			public const int imageAspectRatio = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int imageAspectRatioAdjust = 2130771968;
			
			// aapt resource value: 0x7f010005
			public const int scopeUris = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050008
			public const int common_google_signin_btn_text_dark = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int common_google_signin_btn_text_dark_default = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int common_google_signin_btn_text_dark_disabled = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int common_google_signin_btn_text_dark_focused = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int common_google_signin_btn_text_dark_pressed = 2131034115;
			
			// aapt resource value: 0x7f050009
			public const int common_google_signin_btn_text_light = 2131034121;
			
			// aapt resource value: 0x7f050004
			public const int common_google_signin_btn_text_light_default = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int common_google_signin_btn_text_light_disabled = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int common_google_signin_btn_text_light_focused = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int common_google_signin_btn_text_light_pressed = 2131034119;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int common_full_open_on_phone = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int common_google_signin_btn_icon_dark = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int common_google_signin_btn_icon_dark_disabled = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int common_google_signin_btn_icon_dark_focused = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int common_google_signin_btn_icon_dark_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int common_google_signin_btn_icon_dark_pressed = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int common_google_signin_btn_icon_light = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int common_google_signin_btn_icon_light_disabled = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int common_google_signin_btn_icon_light_focused = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int common_google_signin_btn_icon_light_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int common_google_signin_btn_icon_light_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int common_google_signin_btn_text_dark = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int common_google_signin_btn_text_dark_disabled = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int common_google_signin_btn_text_dark_focused = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int common_google_signin_btn_text_dark_normal = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int common_google_signin_btn_text_dark_pressed = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int common_google_signin_btn_text_light = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int common_google_signin_btn_text_light_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int common_google_signin_btn_text_light_focused = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int common_google_signin_btn_text_light_normal = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int common_google_signin_btn_text_light_pressed = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Photo = 2130837526;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f09003b
			public const int about = 2131296315;
			
			// aapt resource value: 0x7f090039
			public const int adView = 2131296313;
			
			// aapt resource value: 0x7f090000
			public const int adjust_height = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int adjust_width = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int appname_field = 2131296268;
			
			// aapt resource value: 0x7f090006
			public const int auto = 2131296262;
			
			// aapt resource value: 0x7f09003c
			public const int change_city1 = 2131296316;
			
			// aapt resource value: 0x7f09003d
			public const int change_city2 = 2131296317;
			
			// aapt resource value: 0x7f09003e
			public const int change_city3 = 2131296318;
			
			// aapt resource value: 0x7f09003f
			public const int change_city4 = 2131296319;
			
			// aapt resource value: 0x7f09001d
			public const int citi1_layout = 2131296285;
			
			// aapt resource value: 0x7f090024
			public const int citi2_layout = 2131296292;
			
			// aapt resource value: 0x7f09002b
			public const int citi3_layout = 2131296299;
			
			// aapt resource value: 0x7f090032
			public const int citi4_layout = 2131296306;
			
			// aapt resource value: 0x7f090023
			public const int city1_content_buzy = 2131296291;
			
			// aapt resource value: 0x7f09002a
			public const int city2_content_buzy = 2131296298;
			
			// aapt resource value: 0x7f090031
			public const int city3_content_buzy = 2131296305;
			
			// aapt resource value: 0x7f090038
			public const int city4_content_buzy = 2131296312;
			
			// aapt resource value: 0x7f09000f
			public const int city_field = 2131296271;
			
			// aapt resource value: 0x7f090022
			public const int city_field1 = 2131296290;
			
			// aapt resource value: 0x7f090029
			public const int city_field2 = 2131296297;
			
			// aapt resource value: 0x7f090030
			public const int city_field3 = 2131296304;
			
			// aapt resource value: 0x7f090037
			public const int city_field4 = 2131296311;
			
			// aapt resource value: 0x7f090009
			public const int container = 2131296265;
			
			// aapt resource value: 0x7f090014
			public const int current_temperature_field = 2131296276;
			
			// aapt resource value: 0x7f090016
			public const int current_temperature_field_celcius = 2131296278;
			
			// aapt resource value: 0x7f090015
			public const int current_temperature_field_degree = 2131296277;
			
			// aapt resource value: 0x7f090007
			public const int dark = 2131296263;
			
			// aapt resource value: 0x7f090017
			public const int description_field = 2131296279;
			
			// aapt resource value: 0x7f090011
			public const int fahrenheit_switch = 2131296273;
			
			// aapt resource value: 0x7f090040
			public const int help = 2131296320;
			
			// aapt resource value: 0x7f09000e
			public const int helpcontent = 2131296270;
			
			// aapt resource value: 0x7f090018
			public const int humidity_field = 2131296280;
			
			// aapt resource value: 0x7f090003
			public const int icon_only = 2131296259;
			
			// aapt resource value: 0x7f090008
			public const int light = 2131296264;
			
			// aapt resource value: 0x7f09000a
			public const int main_content = 2131296266;
			
			// aapt resource value: 0x7f09003a
			public const int main_content_buzy = 2131296314;
			
			// aapt resource value: 0x7f090002
			public const int none = 2131296258;
			
			// aapt resource value: 0x7f09000b
			public const int photo = 2131296267;
			
			// aapt resource value: 0x7f090019
			public const int pressure_field = 2131296281;
			
			// aapt resource value: 0x7f090004
			public const int standard = 2131296260;
			
			// aapt resource value: 0x7f09001b
			public const int sunrise_field = 2131296283;
			
			// aapt resource value: 0x7f09001c
			public const int sunset_field = 2131296284;
			
			// aapt resource value: 0x7f090013
			public const int temp_container = 2131296275;
			
			// aapt resource value: 0x7f09001f
			public const int temp_field1 = 2131296287;
			
			// aapt resource value: 0x7f090021
			public const int temp_field1_celcius = 2131296289;
			
			// aapt resource value: 0x7f090020
			public const int temp_field1_degree = 2131296288;
			
			// aapt resource value: 0x7f090026
			public const int temp_field2 = 2131296294;
			
			// aapt resource value: 0x7f090028
			public const int temp_field2_celcius = 2131296296;
			
			// aapt resource value: 0x7f090027
			public const int temp_field2_degree = 2131296295;
			
			// aapt resource value: 0x7f09002d
			public const int temp_field3 = 2131296301;
			
			// aapt resource value: 0x7f09002f
			public const int temp_field3_celcius = 2131296303;
			
			// aapt resource value: 0x7f09002e
			public const int temp_field3_degree = 2131296302;
			
			// aapt resource value: 0x7f090034
			public const int temp_field4 = 2131296308;
			
			// aapt resource value: 0x7f090036
			public const int temp_field4_celcius = 2131296310;
			
			// aapt resource value: 0x7f090035
			public const int temp_field4_degree = 2131296309;
			
			// aapt resource value: 0x7f090010
			public const int updated_field = 2131296272;
			
			// aapt resource value: 0x7f09000d
			public const int version_field = 2131296269;
			
			// aapt resource value: 0x7f090012
			public const int weather_icon = 2131296274;
			
			// aapt resource value: 0x7f09001e
			public const int weather_icon1 = 2131296286;
			
			// aapt resource value: 0x7f090025
			public const int weather_icon2 = 2131296293;
			
			// aapt resource value: 0x7f09002c
			public const int weather_icon3 = 2131296300;
			
			// aapt resource value: 0x7f090033
			public const int weather_icon4 = 2131296307;
			
			// aapt resource value: 0x7f090005
			public const int wide = 2131296261;
			
			// aapt resource value: 0x7f09001a
			public const int wind_field = 2131296282;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f070000
			public const int google_play_services_version = 2131165184;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_about = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_help = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_weather = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f080000
			public const int menu1 = 2131230720;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f04001b
			public const int ApplicationName = 2130968603;
			
			// aapt resource value: 0x7f04001c
			public const int about = 2130968604;
			
			// aapt resource value: 0x7f040000
			public const int accept = 2130968576;
			
			// aapt resource value: 0x7f04000a
			public const int common_google_play_services_enable_button = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int common_google_play_services_enable_text = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int common_google_play_services_enable_title = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int common_google_play_services_install_button = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int common_google_play_services_install_text = 2130968590;
			
			// aapt resource value: 0x7f04000f
			public const int common_google_play_services_install_title = 2130968591;
			
			// aapt resource value: 0x7f040010
			public const int common_google_play_services_notification_ticker = 2130968592;
			
			// aapt resource value: 0x7f04001a
			public const int common_google_play_services_unknown_issue = 2130968602;
			
			// aapt resource value: 0x7f040011
			public const int common_google_play_services_unsupported_text = 2130968593;
			
			// aapt resource value: 0x7f040012
			public const int common_google_play_services_update_button = 2130968594;
			
			// aapt resource value: 0x7f040013
			public const int common_google_play_services_update_text = 2130968595;
			
			// aapt resource value: 0x7f040014
			public const int common_google_play_services_update_title = 2130968596;
			
			// aapt resource value: 0x7f040015
			public const int common_google_play_services_updating_text = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int common_google_play_services_wear_update_text = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int common_open_on_phone = 2130968599;
			
			// aapt resource value: 0x7f040018
			public const int common_signin_button_text = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int common_signin_button_text_long = 2130968601;
			
			// aapt resource value: 0x7f040001
			public const int create_calendar_message = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int create_calendar_title = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int debug_menu_ad_information = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int debug_menu_creative_preview = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int debug_menu_title = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int debug_menu_troubleshooting = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int decline = 2130968583;
			
			// aapt resource value: 0x7f04001d
			public const int help = 2130968605;
			
			// aapt resource value: 0x7f040020
			public const int offfahrenheit = 2130968608;
			
			// aapt resource value: 0x7f04001e
			public const int ok = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int onfahrenheit = 2130968607;
			
			// aapt resource value: 0x7f040022
			public const int open_weather_maps_app_id = 2130968610;
			
			// aapt resource value: 0x7f04002b
			public const int place_not_found = 2130968619;
			
			// aapt resource value: 0x7f040008
			public const int store_picture_message = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int store_picture_title = 2130968585;
			
			// aapt resource value: 0x7f040021
			public const int version = 2130968609;
			
			// aapt resource value: 0x7f040024
			public const int weather_clear_night = 2130968612;
			
			// aapt resource value: 0x7f040026
			public const int weather_cloudy = 2130968614;
			
			// aapt resource value: 0x7f04002a
			public const int weather_drizzle = 2130968618;
			
			// aapt resource value: 0x7f040025
			public const int weather_foggy = 2130968613;
			
			// aapt resource value: 0x7f040027
			public const int weather_rainy = 2130968615;
			
			// aapt resource value: 0x7f040028
			public const int weather_snowy = 2130968616;
			
			// aapt resource value: 0x7f040023
			public const int weather_sunny = 2130968611;
			
			// aapt resource value: 0x7f040029
			public const int weather_thunder = 2130968617;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int Theme_IAPTheme = 2131099648;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] AdsAttrs = new int[] {
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int AdsAttrs_adSize = 0;
			
			// aapt resource value: 1
			public const int AdsAttrs_adSizes = 1;
			
			// aapt resource value: 2
			public const int AdsAttrs_adUnitId = 2;
			
			public static int[] LoadingImageView = new int[] {
					2130771968,
					2130771969,
					2130771970};
			
			// aapt resource value: 2
			public const int LoadingImageView_circleCrop = 2;
			
			// aapt resource value: 1
			public const int LoadingImageView_imageAspectRatio = 1;
			
			// aapt resource value: 0
			public const int LoadingImageView_imageAspectRatioAdjust = 0;
			
			public static int[] SignInButton = new int[] {
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int SignInButton_buttonSize = 0;
			
			// aapt resource value: 1
			public const int SignInButton_colorScheme = 1;
			
			// aapt resource value: 2
			public const int SignInButton_scopeUris = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
